### PR TITLE
Edits to abstract

### PR DESCRIPTION
**Pull request by jgabry**
@mhandreae What do you think?

### CODE REVIEW

**Comment by mhandreae** [comment]
I will look at it Monday...
;-)
M.

**Comment by mhandreae** [comment]
Nice. Github worked like a charm. I merged your pull request.
Will you bring a print out to share with Andrew and the crew tomorrow to
discuss where to submit the abstract and where to submit the manuscript?
Cheers
Michael

**Comment by jgabry** [comment]
I'm happy to discuss that. I tried printing it this evening but they seem
to have shut off my printing access. I'll see if I can print it in the
morning but in the worst case we have it on the computer.

See you in the morning,
Jonah

**Comment by mhandreae** [comment]
Will see if I can still print...
;-)
M.

**Pull request merged**
